# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from gusto_app_integrations_python_sdk import GustoAppIntegrations

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        gustoappintegrations = GustoAppIntegrations(
        
                        api_key_auth = 'YOUR_API_KEY',
        
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(gustoappintegrations)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
