# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_app_integrations_python_sdk
from gusto_app_integrations_python_sdk.model.payrolls_update_by_id_request_employee_compensations import PayrollsUpdateByIdRequestEmployeeCompensations
from gusto_app_integrations_python_sdk import configuration


class TestPayrollsUpdateByIdRequestEmployeeCompensations(unittest.TestCase):
    """PayrollsUpdateByIdRequestEmployeeCompensations unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
