# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_app_integrations_python_sdk
from gusto_app_integrations_python_sdk.model.employee_employments_list_terminations_for_employee_response import EmployeeEmploymentsListTerminationsForEmployeeResponse
from gusto_app_integrations_python_sdk import configuration


class TestEmployeeEmploymentsListTerminationsForEmployeeResponse(unittest.TestCase):
    """EmployeeEmploymentsListTerminationsForEmployeeResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
