# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_app_integrations_python_sdk
from gusto_app_integrations_python_sdk.model.contractors_create_individual_or_business_request import ContractorsCreateIndividualOrBusinessRequest
from gusto_app_integrations_python_sdk import configuration


class TestContractorsCreateIndividualOrBusinessRequest(unittest.TestCase):
    """ContractorsCreateIndividualOrBusinessRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
