# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_app_integrations_python_sdk
from gusto_app_integrations_python_sdk.model.earning_types_update_type_by_id_request import EarningTypesUpdateTypeByIdRequest
from gusto_app_integrations_python_sdk import configuration


class TestEarningTypesUpdateTypeByIdRequest(unittest.TestCase):
    """EarningTypesUpdateTypeByIdRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
