# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_app_integrations_python_sdk.type.companies_create_company_request_company import CompaniesCreateCompanyRequestCompany
from gusto_app_integrations_python_sdk.type.companies_create_company_request_user import CompaniesCreateCompanyRequestUser

class RequiredCompaniesCreateCompanyRequest(TypedDict):
    user: CompaniesCreateCompanyRequestUser

    company: CompaniesCreateCompanyRequestCompany

class OptionalCompaniesCreateCompanyRequest(TypedDict, total=False):
    pass

class CompaniesCreateCompanyRequest(RequiredCompaniesCreateCompanyRequest, OptionalCompaniesCreateCompanyRequest):
    pass
