# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCompaniesCreateCompanyRequestCompanyAddressesItem(TypedDict):
    pass

class OptionalCompaniesCreateCompanyRequestCompanyAddressesItem(TypedDict, total=False):
    street_1: str

    street_2: typing.Optional[str]

    city: str

    zip: str

    state: str

    phone: str

    # Whether or not this is a primary address for the company. If set to true, the address will be used as the mailing and filing address for the company and will be added as a work location. If set to false or not included, the address will only be added as a work location for the company. If multiple addresses are included, only one should be marked as primary.
    is_primary: str

class CompaniesCreateCompanyRequestCompanyAddressesItem(RequiredCompaniesCreateCompanyRequestCompanyAddressesItem, OptionalCompaniesCreateCompanyRequestCompanyAddressesItem):
    pass
