# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_app_integrations_python_sdk.type.company_benefits_remove_benefit_response_errors_base import CompanyBenefitsRemoveBenefitResponseErrorsBase

class RequiredCompanyBenefitsRemoveBenefitResponseErrors(TypedDict):
    pass

class OptionalCompanyBenefitsRemoveBenefitResponseErrors(TypedDict, total=False):
    base: CompanyBenefitsRemoveBenefitResponseErrorsBase

class CompanyBenefitsRemoveBenefitResponseErrors(RequiredCompanyBenefitsRemoveBenefitResponseErrors, OptionalCompanyBenefitsRemoveBenefitResponseErrors):
    pass
