# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_app_integrations_python_sdk.type.company_benefits_remove_benefit_response_errors import CompanyBenefitsRemoveBenefitResponseErrors

class RequiredCompanyBenefitsRemoveBenefitResponse(TypedDict):
    pass

class OptionalCompanyBenefitsRemoveBenefitResponse(TypedDict, total=False):
    errors: CompanyBenefitsRemoveBenefitResponseErrors

class CompanyBenefitsRemoveBenefitResponse(RequiredCompanyBenefitsRemoveBenefitResponse, OptionalCompanyBenefitsRemoveBenefitResponse):
    pass
