# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCompaniesCreateCompanyResponse(TypedDict):
    pass

class OptionalCompaniesCreateCompanyResponse(TypedDict, total=False):
    # A URL where the user should be redirected to complete their account setup inside of Gusto.
    account_claim_url: str

class CompaniesCreateCompanyResponse(RequiredCompaniesCreateCompanyResponse, OptionalCompaniesCreateCompanyResponse):
    pass
