# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_app_integrations_python_sdk.type.companies_create_company_request_company_addresses import CompaniesCreateCompanyRequestCompanyAddresses
from gusto_app_integrations_python_sdk.type.companies_create_company_request_company_states import CompaniesCreateCompanyRequestCompanyStates

class RequiredCompaniesCreateCompanyRequestCompany(TypedDict):
    # The legal name of the company.
    name: str

class OptionalCompaniesCreateCompanyRequestCompany(TypedDict, total=False):
    # The name of the company.
    trade_name: str

    # The employer identification number (EIN) of the company.
    ein: str

    states: CompaniesCreateCompanyRequestCompanyStates

    # The number of employees in the company.
    number_employees: typing.Union[int, float]

    addresses: CompaniesCreateCompanyRequestCompanyAddresses

class CompaniesCreateCompanyRequestCompany(RequiredCompaniesCreateCompanyRequestCompany, OptionalCompaniesCreateCompanyRequestCompany):
    pass
