# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_app_integrations_python_sdk.type.departments_remove_employees_request_contractors import DepartmentsRemoveEmployeesRequestContractors
from gusto_app_integrations_python_sdk.type.departments_remove_employees_request_employees import DepartmentsRemoveEmployeesRequestEmployees

class RequiredDepartmentsRemoveEmployeesRequest(TypedDict):
    pass

class OptionalDepartmentsRemoveEmployeesRequest(TypedDict, total=False):
    # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field.
    version: str

    employees: DepartmentsRemoveEmployeesRequestEmployees

    contractors: DepartmentsRemoveEmployeesRequestContractors

class DepartmentsRemoveEmployeesRequest(RequiredDepartmentsRemoveEmployeesRequest, OptionalDepartmentsRemoveEmployeesRequest):
    pass
