# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_company_benefits.post import CreateCompanyBenefitRaw
from gusto_app_integrations_python_sdk.paths.v1_benefits.get import GetAllSupportedBenefitsRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_company_benefits.get import GetByCompanyIdRaw
from gusto_app_integrations_python_sdk.paths.v1_company_benefits_company_benefit_id.get import GetByIdRaw
from gusto_app_integrations_python_sdk.paths.v1_benefits_benefit_id_requirements.get import GetFieldsRequirementsByIdRaw
from gusto_app_integrations_python_sdk.paths.v1_company_benefits_company_benefit_id_summary.get import GetSummaryByIdRaw
from gusto_app_integrations_python_sdk.paths.v1_benefits_benefit_id.get import GetSupportedBenefitByIdRaw
from gusto_app_integrations_python_sdk.paths.v1_company_benefits_company_benefit_id.delete import RemoveBenefitRaw
from gusto_app_integrations_python_sdk.paths.v1_company_benefits_company_benefit_id.put import UpdateBenefitRaw


class CompanyBenefitsApiRaw(
    CreateCompanyBenefitRaw,
    GetAllSupportedBenefitsRaw,
    GetByCompanyIdRaw,
    GetByIdRaw,
    GetFieldsRequirementsByIdRaw,
    GetSummaryByIdRaw,
    GetSupportedBenefitByIdRaw,
    RemoveBenefitRaw,
    UpdateBenefitRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
