# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_provision.post import CreateCompany
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id.get import GetCompanyInfo
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_custom_fields.get import GetCustomFields
from gusto_app_integrations_python_sdk.apis.tags.companies_api_raw import CompaniesApiRaw


class CompaniesApi(
    CreateCompany,
    GetCompanyInfo,
    GetCustomFields,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CompaniesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CompaniesApiRaw(api_client)
