# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_provision.post import CreateCompanyRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id.get import GetCompanyInfoRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_custom_fields.get import GetCustomFieldsRaw


class CompaniesApiRaw(
    CreateCompanyRaw,
    GetCompanyInfoRaw,
    GetCustomFieldsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
