# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_contractors.post import CreateIndividualOrBusiness
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_contractors.get import GetAll
from gusto_app_integrations_python_sdk.paths.v1_contractors_contractor_id.get import GetDetails
from gusto_app_integrations_python_sdk.paths.v1_contractors_contractor_id.put import UpdateContractor
from gusto_app_integrations_python_sdk.apis.tags.contractors_api_raw import ContractorsApiRaw


class ContractorsApi(
    CreateIndividualOrBusiness,
    GetAll,
    GetDetails,
    UpdateContractor,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ContractorsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ContractorsApiRaw(api_client)
