# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_contractor_payments_contractor_payment_id.get import GetSingle
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_contractor_payments.get import ListForCompany
from gusto_app_integrations_python_sdk.apis.tags.contractor_payments_api_raw import ContractorPaymentsApiRaw


class ContractorPaymentsApi(
    GetSingle,
    ListForCompany,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ContractorPaymentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ContractorPaymentsApiRaw(api_client)
