# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_departments_department_uuid_add.put import AddPeopleToDepartment
from gusto_app_integrations_python_sdk.paths.v1_companies_company_uuid_departments.post import CreateDepartment
from gusto_app_integrations_python_sdk.paths.v1_departments_department_uuid.delete import DeleteDepartment
from gusto_app_integrations_python_sdk.paths.v1_departments_department_uuid.get import GetByUuid
from gusto_app_integrations_python_sdk.paths.v1_companies_company_uuid_departments.get import ListForCompany
from gusto_app_integrations_python_sdk.paths.v1_departments_department_uuid_remove.put import RemoveEmployees
from gusto_app_integrations_python_sdk.paths.v1_departments_department_uuid.put import UpdateDepartment
from gusto_app_integrations_python_sdk.apis.tags.departments_api_raw import DepartmentsApiRaw


class DepartmentsApi(
    AddPeopleToDepartment,
    CreateDepartment,
    DeleteDepartment,
    GetByUuid,
    ListForCompany,
    RemoveEmployees,
    UpdateDepartment,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DepartmentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DepartmentsApiRaw(api_client)
