# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_rehire.post import CreateRehire
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_terminations.post import CreateTermination
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_rehire.delete import DeleteRehire
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_terminations.delete import DeleteTermination
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_employment_history.get import GetHistory
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_rehire.get import GetRehireInfo
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_terminations.get import ListTerminationsForEmployee
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_rehire.put import UpdateRehire
from gusto_app_integrations_python_sdk.paths.v1_terminations_employee_id.put import UpdateTermination
from gusto_app_integrations_python_sdk.apis.tags.employee_employments_api_raw import EmployeeEmploymentsApiRaw


class EmployeeEmploymentsApi(
    CreateRehire,
    CreateTermination,
    DeleteRehire,
    DeleteTermination,
    GetHistory,
    GetRehireInfo,
    ListTerminationsForEmployee,
    UpdateRehire,
    UpdateTermination,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeeEmploymentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeeEmploymentsApiRaw(api_client)
