# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_employees.post import CreateEmployee
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id.delete import DeleteOnboardingEmployee
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_employees.get import GetCompanyEmployees
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_custom_fields.get import GetCustomFields
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id.get import GetDetails
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_uuid_time_off_activities.get import GetTimeOffActivities
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id.put import UpdateEmployee
from gusto_app_integrations_python_sdk.apis.tags.employees_api_raw import EmployeesApiRaw


class EmployeesApi(
    CreateEmployee,
    DeleteOnboardingEmployee,
    GetCompanyEmployees,
    GetCustomFields,
    GetDetails,
    GetTimeOffActivities,
    UpdateEmployee,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeesApiRaw(api_client)
