# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_garnishments.post import CreateGarnishmentRaw
from gusto_app_integrations_python_sdk.paths.v1_garnishments_garnishment_id.get import GetRaw
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_garnishments.get import GetEmployeeGarnishmentsRaw
from gusto_app_integrations_python_sdk.paths.v1_garnishments_garnishment_id.put import UpdateRaw


class GarnishmentsApiRaw(
    CreateGarnishmentRaw,
    GetRaw,
    GetEmployeeGarnishmentsRaw,
    UpdateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
