# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_token_info.get import AccessTokenInfo
from gusto_app_integrations_python_sdk.paths.oauth_token.post import ExchangeRefreshToken
from gusto_app_integrations_python_sdk.apis.tags.introspection_api_raw import IntrospectionApiRaw


class IntrospectionApi(
    AccessTokenInfo,
    ExchangeRefreshToken,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: IntrospectionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = IntrospectionApiRaw(api_client)
