# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_token_info.get import AccessTokenInfoRaw
from gusto_app_integrations_python_sdk.paths.oauth_token.post import ExchangeRefreshTokenRaw


class IntrospectionApiRaw(
    AccessTokenInfoRaw,
    ExchangeRefreshTokenRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
