# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id_compensations.post import CreateCompensationRaw
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_jobs.post import CreateJobRaw
from gusto_app_integrations_python_sdk.paths.v1_compensations_compensation_id.delete import DeleteCompensationRaw
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id.delete import DeleteSpecificJobRaw
from gusto_app_integrations_python_sdk.paths.v1_compensations_compensation_id.get import GetCompensationByIdRaw
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id_compensations.get import GetCompensationsByJobIdRaw
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id.get import GetDetailsRaw
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_jobs.get import GetEmployeeJobsRaw
from gusto_app_integrations_python_sdk.paths.v1_compensations_compensation_id.put import UpdateCompensationRaw
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id.put import UpdateJobRaw


class JobsAndCompensationsApiRaw(
    CreateCompensationRaw,
    CreateJobRaw,
    DeleteCompensationRaw,
    DeleteSpecificJobRaw,
    GetCompensationByIdRaw,
    GetCompensationsByJobIdRaw,
    GetDetailsRaw,
    GetEmployeeJobsRaw,
    UpdateCompensationRaw,
    UpdateJobRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
