# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id_compensations.post import CreateCompensation
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_jobs.post import CreateJob
from gusto_app_integrations_python_sdk.paths.v1_compensations_compensation_id.delete import DeleteCompensation
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id.delete import DeleteSpecificJob
from gusto_app_integrations_python_sdk.paths.v1_compensations_compensation_id.get import GetCompensationById
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id_compensations.get import GetCompensationsByJobId
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id.get import GetDetails
from gusto_app_integrations_python_sdk.paths.v1_employees_employee_id_jobs.get import GetEmployeeJobs
from gusto_app_integrations_python_sdk.paths.v1_compensations_compensation_id.put import UpdateCompensation
from gusto_app_integrations_python_sdk.paths.v1_jobs_job_id.put import UpdateJob
from gusto_app_integrations_python_sdk.apis.tags.jobs_and_compensations_api_raw import JobsAndCompensationsApiRaw


class JobsAndCompensationsApi(
    CreateCompensation,
    CreateJob,
    DeleteCompensation,
    DeleteSpecificJob,
    GetCompensationById,
    GetCompensationsByJobId,
    GetDetails,
    GetEmployeeJobs,
    UpdateCompensation,
    UpdateJob,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobsAndCompensationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobsAndCompensationsApiRaw(api_client)
