# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_locations.post import CreateCompanyLocationRaw
from gusto_app_integrations_python_sdk.paths.v1_locations_location_id.get import GetDetailsRaw
from gusto_app_integrations_python_sdk.paths.v1_locations_location_uuid_minimum_wages.get import GetMinimumWagesRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_locations.get import ListCompanyLocationsRaw
from gusto_app_integrations_python_sdk.paths.v1_locations_location_id.put import UpdateLocationRaw


class LocationsApiRaw(
    CreateCompanyLocationRaw,
    GetDetailsRaw,
    GetMinimumWagesRaw,
    ListCompanyLocationsRaw,
    UpdateLocationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
