# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_schedules_assignments.get import GetAssignments
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_schedules_pay_schedule_id.get import GetDetails
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_schedules.get import List
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_periods.get import List0
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_periods_unprocessed_termination_pay_periods.get import ListUnprocessedTerminationPayPeriods
from gusto_app_integrations_python_sdk.apis.tags.pay_schedules_api_raw import PaySchedulesApiRaw


class PaySchedulesApi(
    GetAssignments,
    GetDetails,
    List,
    List0,
    ListUnprocessedTerminationPayPeriods,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaySchedulesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaySchedulesApiRaw(api_client)
