# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_schedules_assignments.get import GetAssignmentsRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_schedules_pay_schedule_id.get import GetDetailsRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_schedules.get import ListRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_periods.get import List0Raw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_pay_periods_unprocessed_termination_pay_periods.get import ListUnprocessedTerminationPayPeriodsRaw


class PaySchedulesApiRaw(
    GetAssignmentsRaw,
    GetDetailsRaw,
    ListRaw,
    List0Raw,
    ListUnprocessedTerminationPayPeriodsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
