# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls.get import GetAllForCompanyRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls_payroll_id.get import GetSinglePayrollRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls_payroll_id_prepare.put import PrepareForUpdateRaw
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls_payroll_id.put import UpdateByIdRaw


class PayrollsApiRaw(
    GetAllForCompanyRaw,
    GetSinglePayrollRaw,
    PrepareForUpdateRaw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
