# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls.get import GetAllForCompany
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls_payroll_id.get import GetSinglePayroll
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls_payroll_id_prepare.put import PrepareForUpdate
from gusto_app_integrations_python_sdk.paths.v1_companies_company_id_payrolls_payroll_id.put import UpdateById
from gusto_app_integrations_python_sdk.apis.tags.payrolls_api_raw import PayrollsApiRaw


class PayrollsApi(
    GetAllForCompany,
    GetSinglePayroll,
    PrepareForUpdate,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PayrollsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PayrollsApiRaw(api_client)
