# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_app_integrations_python_sdk.paths.v1_payrolls_payroll_id_employees_employee_id_calculate_accruing_time_off_hours.post import CalculateAccruingTimeOffHours
from gusto_app_integrations_python_sdk.apis.tags.time_off_policies_api_raw import TimeOffPoliciesApiRaw


class TimeOffPoliciesApi(
    CalculateAccruingTimeOffHours,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimeOffPoliciesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimeOffPoliciesApiRaw(api_client)
