# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import gusto_app_integrations_python_sdk
from gusto_app_integrations_python_sdk.paths.v1_provision import post
from gusto_app_integrations_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1Provision(ApiTestMixin, unittest.TestCase):
    """
    V1Provision unit test stubs
        Create a company
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201




if __name__ == '__main__':
    unittest.main()
