# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from gusto_app_integrations_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_TOKEN_INFO = "/v1/token_info"
    OAUTH_TOKEN = "/oauth/token"
    V1_PROVISION = "/v1/provision"
    V1_COMPANIES_COMPANY_ID = "/v1/companies/{company_id}"
    V1_COMPANIES_COMPANY_ID_CUSTOM_FIELDS = "/v1/companies/{company_id}/custom_fields"
    V1_COMPANIES_COMPANY_ID_LOCATIONS = "/v1/companies/{company_id}/locations"
    V1_LOCATIONS_LOCATION_ID = "/v1/locations/{location_id}"
    V1_LOCATIONS_LOCATION_UUID_MINIMUM_WAGES = "/v1/locations/{location_uuid}/minimum_wages"
    V1_COMPANIES_COMPANY_ID_PAY_SCHEDULES = "/v1/companies/{company_id}/pay_schedules"
    V1_COMPANIES_COMPANY_ID_PAY_SCHEDULES_PAY_SCHEDULE_ID = "/v1/companies/{company_id}/pay_schedules/{pay_schedule_id}"
    V1_COMPANIES_COMPANY_ID_PAY_PERIODS = "/v1/companies/{company_id}/pay_periods"
    V1_COMPANIES_COMPANY_ID_PAY_PERIODS_UNPROCESSED_TERMINATION_PAY_PERIODS = "/v1/companies/{company_id}/pay_periods/unprocessed_termination_pay_periods"
    V1_COMPANIES_COMPANY_ID_PAY_SCHEDULES_ASSIGNMENTS = "/v1/companies/{company_id}/pay_schedules/assignments"
    V1_COMPANIES_COMPANY_ID_EMPLOYEES = "/v1/companies/{company_id}/employees"
    V1_COMPANIES_COMPANY_UUID_DEPARTMENTS = "/v1/companies/{company_uuid}/departments"
    V1_DEPARTMENTS_DEPARTMENT_UUID = "/v1/departments/{department_uuid}"
    V1_DEPARTMENTS_DEPARTMENT_UUID_ADD = "/v1/departments/{department_uuid}/add"
    V1_DEPARTMENTS_DEPARTMENT_UUID_REMOVE = "/v1/departments/{department_uuid}/remove"
    V1_EMPLOYEES_EMPLOYEE_ID = "/v1/employees/{employee_id}"
    V1_EMPLOYEES_EMPLOYEE_ID_TERMINATIONS = "/v1/employees/{employee_id}/terminations"
    V1_TERMINATIONS_EMPLOYEE_ID = "/v1/terminations/{employee_id}"
    V1_EMPLOYEES_EMPLOYEE_ID_REHIRE = "/v1/employees/{employee_id}/rehire"
    V1_EMPLOYEES_EMPLOYEE_ID_EMPLOYMENT_HISTORY = "/v1/employees/{employee_id}/employment_history"
    V1_EMPLOYEES_EMPLOYEE_ID_HOME_ADDRESSES = "/v1/employees/{employee_id}/home_addresses"
    V1_HOME_ADDRESSES_HOME_ADDRESS_UUID = "/v1/home_addresses/{home_address_uuid}"
    V1_EMPLOYEES_EMPLOYEE_ID_WORK_ADDRESSES = "/v1/employees/{employee_id}/work_addresses"
    V1_WORK_ADDRESSES_WORK_ADDRESS_UUID = "/v1/work_addresses/{work_address_uuid}"
    V1_EMPLOYEES_EMPLOYEE_ID_CUSTOM_FIELDS = "/v1/employees/{employee_id}/custom_fields"
    V1_EMPLOYEES_EMPLOYEE_ID_JOBS = "/v1/employees/{employee_id}/jobs"
    V1_EMPLOYEES_EMPLOYEE_UUID_TIME_OFF_ACTIVITIES = "/v1/employees/{employee_uuid}/time_off_activities"
    V1_JOBS_JOB_ID = "/v1/jobs/{job_id}"
    V1_JOBS_JOB_ID_COMPENSATIONS = "/v1/jobs/{job_id}/compensations"
    V1_COMPENSATIONS_COMPENSATION_ID = "/v1/compensations/{compensation_id}"
    V1_COMPANIES_COMPANY_ID_EARNING_TYPES = "/v1/companies/{company_id}/earning_types"
    V1_COMPANIES_COMPANY_ID_EARNING_TYPES_EARNING_TYPE_UUID = "/v1/companies/{company_id}/earning_types/{earning_type_uuid}"
    V1_COMPANIES_COMPANY_ID_CONTRACTORS = "/v1/companies/{company_id}/contractors"
    V1_CONTRACTORS_CONTRACTOR_ID = "/v1/contractors/{contractor_id}"
    V1_WEBHOOK_SUBSCRIPTIONS = "/v1/webhook_subscriptions"
    V1_WEBHOOK_SUBSCRIPTIONS_WEBHOOK_SUBSCRIPTION_UUID = "/v1/webhook_subscriptions/{webhook_subscription_uuid}"
    V1_WEBHOOK_SUBSCRIPTIONS_WEBHOOK_SUBSCRIPTION_UUID_VERIFY = "/v1/webhook_subscriptions/{webhook_subscription_uuid}/verify"
    V1_WEBHOOK_SUBSCRIPTIONS_WEBHOOK_SUBSCRIPTION_UUID_REQUEST_VERIFICATION_TOKEN = "/v1/webhook_subscriptions/{webhook_subscription_uuid}/request_verification_token"
    V1_COMPANIES_COMPANY_ID_PAYROLLS = "/v1/companies/{company_id}/payrolls"
    V1_COMPANIES_COMPANY_ID_PAYROLLS_PAYROLL_ID = "/v1/companies/{company_id}/payrolls/{payroll_id}"
    V1_COMPANIES_COMPANY_ID_PAYROLLS_PAYROLL_ID_PREPARE = "/v1/companies/{company_id}/payrolls/{payroll_id}/prepare"
    V1_PAYROLLS_PAYROLL_ID_EMPLOYEES_EMPLOYEE_ID_CALCULATE_ACCRUING_TIME_OFF_HOURS = "/v1/payrolls/{payroll_id}/employees/{employee_id}/calculate_accruing_time_off_hours"
    V1_COMPANIES_COMPANY_ID_CONTRACTOR_PAYMENTS = "/v1/companies/{company_id}/contractor_payments"
    V1_COMPANIES_COMPANY_ID_CONTRACTOR_PAYMENTS_CONTRACTOR_PAYMENT_ID = "/v1/companies/{company_id}/contractor_payments/{contractor_payment_id}"
    V1_COMPANIES_COMPANY_ID_COMPANY_BENEFITS = "/v1/companies/{company_id}/company_benefits"
    V1_COMPANY_BENEFITS_COMPANY_BENEFIT_ID = "/v1/company_benefits/{company_benefit_id}"
    V1_BENEFITS = "/v1/benefits"
    V1_BENEFITS_BENEFIT_ID = "/v1/benefits/{benefit_id}"
    V1_COMPANY_BENEFITS_COMPANY_BENEFIT_ID_SUMMARY = "/v1/company_benefits/{company_benefit_id}/summary"
    V1_BENEFITS_BENEFIT_ID_REQUIREMENTS = "/v1/benefits/{benefit_id}/requirements"
    V1_EMPLOYEES_EMPLOYEE_ID_EMPLOYEE_BENEFITS = "/v1/employees/{employee_id}/employee_benefits"
    V1_EMPLOYEE_BENEFITS_EMPLOYEE_BENEFIT_ID = "/v1/employee_benefits/{employee_benefit_id}"
    V1_EMPLOYEES_EMPLOYEE_ID_YTD_BENEFIT_AMOUNTS_FROM_DIFFERENT_COMPANY = "/v1/employees/{employee_id}/ytd_benefit_amounts_from_different_company"
    V1_EMPLOYEES_EMPLOYEE_ID_GARNISHMENTS = "/v1/employees/{employee_id}/garnishments"
    V1_GARNISHMENTS_GARNISHMENT_ID = "/v1/garnishments/{garnishment_id}"
    V1_EVENTS = "/v1/events"
