# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_app_integrations_python_sdk import schemas  # noqa: F401


class PayrollsUpdateByIdRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "employee_compensations",
        }
        
        class properties:
        
            @staticmethod
            def employee_compensations() -> typing.Type['PayrollsUpdateByIdRequestEmployeeCompensations']:
                return PayrollsUpdateByIdRequestEmployeeCompensations
            __annotations__ = {
                "employee_compensations": employee_compensations,
            }
    
    employee_compensations: 'PayrollsUpdateByIdRequestEmployeeCompensations'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee_compensations"]) -> 'PayrollsUpdateByIdRequestEmployeeCompensations': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["employee_compensations", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee_compensations"]) -> 'PayrollsUpdateByIdRequestEmployeeCompensations': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["employee_compensations", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        employee_compensations: 'PayrollsUpdateByIdRequestEmployeeCompensations',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayrollsUpdateByIdRequest':
        return super().__new__(
            cls,
            *args,
            employee_compensations=employee_compensations,
            _configuration=_configuration,
            **kwargs,
        )

from gusto_app_integrations_python_sdk.model.payrolls_update_by_id_request_employee_compensations import PayrollsUpdateByIdRequestEmployeeCompensations
