# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_app_integrations_python_sdk import schemas  # noqa: F401


class WebhooksUpdateSubscriptionByUuidRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "subscription_types",
        }
        
        class properties:
        
            @staticmethod
            def subscription_types() -> typing.Type['WebhooksUpdateSubscriptionByUuidRequestSubscriptionTypes']:
                return WebhooksUpdateSubscriptionByUuidRequestSubscriptionTypes
            __annotations__ = {
                "subscription_types": subscription_types,
            }
    
    subscription_types: 'WebhooksUpdateSubscriptionByUuidRequestSubscriptionTypes'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subscription_types"]) -> 'WebhooksUpdateSubscriptionByUuidRequestSubscriptionTypes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["subscription_types", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subscription_types"]) -> 'WebhooksUpdateSubscriptionByUuidRequestSubscriptionTypes': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["subscription_types", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        subscription_types: 'WebhooksUpdateSubscriptionByUuidRequestSubscriptionTypes',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WebhooksUpdateSubscriptionByUuidRequest':
        return super().__new__(
            cls,
            *args,
            subscription_types=subscription_types,
            _configuration=_configuration,
            **kwargs,
        )

from gusto_app_integrations_python_sdk.model.webhooks_update_subscription_by_uuid_request_subscription_types import WebhooksUpdateSubscriptionByUuidRequestSubscriptionTypes
